#!/bin/bash
SECONDS=0
Value=0
While [1]
        do
        value=$(( $value + 1 ))
        duration=$SECONDS
        min=$(($duration / 60))
        sec=$(($duration / 60))
        echo “$min minutes and $sec seconds elapsed
        echo “The program has been running $value times so far.”
        ./stack
done

export MYSHELL=/bin/sh
env | grep MYSHELL


#include <stdio.h>
#include <stdlib.h>

void main()
{
    char* shell = getenv(“MYSHELL);
    if (shell)
        printf(“%x\n”, (unsigned int)shell);
}



/ getenv.c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
int main(int argc, char const *argv[])
{
    char *ptr;
    if(argc < 3)
    {
        printf("Usage: %s <environment var> <target program name>\n", argv[0]);
        exit(0);
    }
    ptr = getenv(argv[1]);
    ptr += (strlen(argv[0]) - strlen(argv[2])) * 2;
    printf("%s will be at %p\n", argv[1], ptr);
    return 0;
}
