#!/bin/bash
SECONDS=0
Value=0
While [1]
        do
        value=$(( $value + 1 ))
        duration=$SECONDS
        min=$(($duration / 60))
        sec=$(($duration / 60))
        echo “$min minutes and $sec seconds elapsed
        echo “The program has been running $value times so far.”
        ./stack
done

export MYSHELL=/bin/sh
env | grep MYSHELL


#include <stdio.h>
#include <stdlib.h>

void main()
{
    char* shell = getenv(“MYSHELL);
    if (shell)
        printf(“%x\n”, (unsigned int)shell);
}
